# -*- coding: utf-8 -*-
"""YOLOv10_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zGSSvGCPk1J6EusO5xzfXYHUJ5hfWme

#Pre-trained Model
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics

!git clone https://github.com/THU-MIG/yolov10.git

!wget https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10.pt

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov10
!pip install -q -r requirements.txt
!pip install -e.

from ultralytics import YOLOv10
MODEL_PATH = '/content/yolov10/yolov10n.pt'
model = YOLOv10(MODEL_PATH)

!gdown '1tr9PSRRdlC2pNir7jsYugpSMG-7v32VJ' -O './images/'

"""#Using Model"""

IMAGE_PATH = '/content/yolov10/images/HCMC_Street.jp'
result = model( source = IMAGE_PATH)[0]
result.save('./images/HCMC_Street_predict.png')

VIDEO_PATH = 'https://www.youtube.com/watch?v=Gr0HpDM8Ki8&list=PLcQZGj9lFR7y5WikozDSrdk6UCtAnM9mB&index=5'
video_result = model(source = VIDEO_PATH)